
# Load necessary libraries
library(quantmod)
library(TTR)

# Get historical data for a stock, e.g., Apple Inc. (AAPL)
getSymbols("AAPL", from = "2020-01-01", to = "2023-01-01", src = "yahoo")

# Inspect the data
head(AAPL)

# Define the moving averages
short_ma <- 20  # Short-term moving average
long_ma <- 50   # Long-term moving average

# Calculate the moving averages
AAPL$SMA20 <- SMA(Cl(AAPL), n = short_ma)
AAPL$SMA50 <- SMA(Cl(AAPL), n = long_ma)

# Define the trading signals
AAPL$Signal <- ifelse(AAPL$SMA20 > AAPL$SMA50, 1, 0)

# Lag the signal to avoid look-ahead bias
AAPL$Signal <- Lag(AAPL$Signal)

# Calculate daily returns
AAPL$Returns <- dailyReturn(Cl(AAPL))

# Calculate strategy returns
AAPL$StrategyReturns <- AAPL$Signal * AAPL$Returns

# Remove NAs (generated by Lag function)
AAPL <- na.omit(AAPL)

# Performance summary
cumulative_returns <- cumprod(1 + AAPL$StrategyReturns) - 1
buy_and_hold_returns <- cumprod(1 + AAPL$Returns) - 1

# Plot the strategy performance vs. buy and hold
plot(cumulative_returns, main = "Cumulative Returns of Strategy vs. Buy & Hold",
		col = "blue", lwd = 2)
lines(buy_and_hold_returns, col = "red", lwd = 2)
legend("topright", legend = c("Strategy", "Buy & Hold"),
		col = c("blue", "red"), lwd = 2)

# Calculate final returns
final_strategy_return <- tail(cumulative_returns, 1)
final_buy_and_hold_return <- tail(buy_and_hold_returns, 1)

cat("Final Strategy Return: ", final_strategy_return, "\n")
cat("Final Buy & Hold Return: ", final_buy_and_hold_return, "\n")
